apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  HOST: https://matchmakerbot.net:80
  MONGO_HOST: mongo-service.mongo.svc.cluster.local
