apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-deployment"
  name: "{{ .Release.Name }}-service"
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30100
  selector:
    app: "{{ .Release.Name }}-deployment"
