apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}-service"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "{{ .Release.Name }}"
