name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint-and-build:
    name: Run eslint and build
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install
      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: lint
      - name: Build
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build
  build:
    name: Build docker container
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Login to github docker
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.PACKAGES_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ github.event.repository.name }} .
      - name: Docker tag
        run: docker tag bot ghcr.io/matchmakerbot/${{ github.event.repository.name }}:latest
      - name: Push docker image
        run: docker push ghcr.io/matchmakerbot/${{ github.event.repository.name }}:latest
